name: CustomBukkitEvents
version: '1.0'
main: me.overkidding.bukkitevents.CustomBukkitEvents
api-version: 1.18
authors: [ overkidding ]
description: Makes creating some type of plugins easier
website: https://www.edenmine.eu
